### ISSUE TITLE
Does nsprintf work with xngettext?

### ISSUE THREAD

**Issue by richierocks** [RL10N/nsprintf#1]
I have vague recollections of `tools::xngettext` being pretty stupid, and not finding calls to `ngettext` that were nested inside functions from other packages.

I don't know if this is still the case, but we need to make sure that calls to `nsprintf` can be turned into PO file content.

**Comment by leeper** [comment]
That would be bad. I haven't tested it. If it doesn't work, perhaps we need to investigate xngettext more and possibly patch it.

 I'm not even sure the way I have written this necessarily makes sense (it is only a small reduction in verbosity).

**Comment by richierocks** [comment]
Grr.  It doesn't work.  Try:

``` r
tmp <- tempfile("R/", fileext = ".R")
dir.create(file.path(tempdir(), "R"))
cat(
  'my_msgs <- function()
{
  ngettext(1, "ngettext one", "ngettext not one")
  nsprintf(1, "nsprintf one", "nsprintf not one")
}', 
  sep = "\n", 
  file = tmp
)
tools::xngettext(tempdir(), verbose = TRUE)
```

I think you're right that `xngettext` (and likely `xgettext` too) need patching/rewriting.

**Comment by leeper** [comment]
Yes, I think the issue in `xgettext()` is here: https://github.com/wch/r-source/blob/trunk/src/library/tools/R/xgettext.R#L45-L56. Seems to only be looking for top-level expressions, whereas it should be looking for any mention of `gettext()` or `ngettext()`. That would also require more comprehensive navigation of the parse tree...ugh.

**Comment by richierocks** [comment]
The cheap-but-not-very-satifsying fix is that we maintain our own copy of
the function, changing it to search for nsprintf too.  But yeah, navigating
the parse tree is the way to do it properly, and I second your "ugh".

On 24 February 2016 at 17:23, Thomas J. Leeper notifications@github.com
wrote:

> Yes, I think the issue in xgettext() is here:
> https://github.com/wch/r-source/blob/trunk/src/library/tools/R/xgettext.R#L45-L56.
> Seems to only be looking for top-level expressions, whereas it should be
> looking for any mention of gettext() or ngettext(). That would also
> require more comprehensive navigation of the parse tree...ugh.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RL10N/nsprintf/issues/1#issuecomment-188274966.

## 

Regards,
Richie

Learning R http://shop.oreilly.com/product/0636920028352.do
4dpiecharts.com

**Comment by leeper** [comment]
And actually there's another layer to it: `xgettext()` is only going to look in the package namespace, not traverse through imported functions (so an add-on package A with translations that calls an untranslated package B is still going to report untranslated errors from package B and I don't think there's anyway to change that without copying the function from B).

So, that may make the whole idea of this package pointless...

**Comment by richierocks** [comment]
When I woke up this morning I had a great idea to use `trace`, since you don't need to know where `nsprintf` is, you just need to call it.  Now that I'm more awake, I realise that the problem with this is we'd have have find a way of ensuring that we actually call the function.  That is, we'd have to evaluate all possible code branches in a package.  So also a no go.

It isn't looking too hopeful for this right now, so maybe best if we put this package on hold.

**Comment by leeper** [comment]
Agreed.
